version: "2"
services:
  metallic:
    restart: unless-stopped
    image: "ghcr.io/natant-network/metallic-docker:main"
    ports:
    #IMPORTANT: DO NOT CHANGE 8080!
      - <your port here>:8080
# network config if youi want a network config feel free to use the one below and change the name to your liking. YOU MUST RUN docker network create <your name> BEFORE RUNNING THE CONTAINER
#networks:
#  default:
#    external:
#      name: default
